#!/bin/sh

#==================================================================================================
#title           :setup-os
#description     :Setup the Alpine Linux base system
#author          :Wesley van Tilburg
#license         :MIT
#date            :01/09/2022
#version         :0.1    
#notes           :Variables are obtained from the read-recipe script
#==================================================================================================

#========== Functionality ==========

Get_Interface(){

 #Check if wired or wireless
 ipaddr | grep -E "wlan[0-9]"
 if [ "$?" -eq 0 ]; then 
	 : ${INTERFACE="$(ipaddr | grep -E "wlan[0-9]" | awk -F: '{print $2}' | tr -d '\n' | tr -d ' ') "}
	 WIRED="FALSE"
 else
	 : ${INTERFACE="$(ipaddr | grep -E "eth[0-9]" | awk -F: '{print $2}' | tr -d '\n' | tr -d ' ') "}
	 WIRED="TRUE"
 fi

}


Create_Answer(){

 #Create interface settings for the answer file
 if [ "$INET" == "static" ]; then
 	NET_VARS="$(echo -e "	address $IP
     	 netmask $NETMASK
    	 gateway $GATEWAY")"
 else
	NET_VARS="$(echo -e "hostname $HOST")"
 fi

 #Create answer file for setup-alpine
 cat <<EOF >> ./answer
 KEYMAPOPTS="$KEYMAP"
 HOSTNAMEOPTS="-n $HOST"
 DEVDOPTS=mdev

 # Contents of /etc/network/interfaces
 iface lo inet loopback

 auto $INTERFACE
    iface $(echo $INTERFACE | cut -c1-4) inet $INET
     $NET_VARS
 "

 DNSOPTS="-d $HOST.local 1.1.1.1"

 TIMEZONEOPTS="-z $TIMEZONE"
 PROXYOPTS=none
 APKREPOSOPTS="-1"

 USEROPTS="-a -u -g wheel $USERNAME"
 SSHDOPTS=openssh
 NTPOPTS="openntpd"
 DISKOPTS="-m sys $DISK"
 LBUOPTS=none
 APKCACHEOPTS=none

EOF

}

Setup(){

 #Install the system 
 yes | setup-alpine -f ./answer
 rm ./answer

 #Mount partitions for the choot
 mount -t ext4 $DISK /mnt
 mount -t sysfs sys /mnt/sys
 mount -o bind /dev /mnt/dev
 cat /etc/resolv.conf >> /mnt/etc/resolv.conf

 #Setup repos
 cat << EOF | chroot /mnt /bin/sh
  cat > /etc/apk/repositories << EOF2; $(echo)
  https://dl-cdn.alpinelinux.org/alpine/latest-stable/main
  https://dl-cdn.alpinelinux.org/alpine/latest-stable/community
 EOF2
 apk update
 apk upgrade -a
EOF

#Unmount chroot
 mount /mnt/sys
 umount /mnt/dev
 umount /mnt

#boot into the new machine
 reboot

}


Create_Answer
Setup




